spring:
  application:
    name: mediator-service

  session:
    max:
      per-user: 3

server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.websocket: DEBUG
