spring:
  application:
    name: notification-service

  config:
    import: optional:file:.env[.properties]

app:
  websocket:
    endpoint: /ws/notifications

server:
  port: 8082

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.websocket: DEBUG
