services:
  mediator-service:
    container_name: mediator-service
    env_file:
      - .env
    build:
      context: .
      dockerfile: /deploy/mediator-service.Dockerfile
    ports:
      - "8080:${SERVER_PORT}"
    depends_on:
      - kafka
    networks:
      - app-network

  security-service:
    container_name: security-service
    env_file:
      - .env
    build:
      context: .
      dockerfile: /deploy/security-service.Dockerfile
    ports:
      - "8081:${SERVER_PORT}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-security:${SECURITY_SERVICE_POSTGRES_PORT}/${SECURITY_SERVICE_POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${SECURITY_SERVICE_POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SECURITY_SERVICE_POSTGRES_PASSWORD}
      SPRING_JWT_SECRET: ${JWT_SECRET}
      SPRING_JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      SPRING_JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
    depends_on:
      - postgres-security
    networks:
      - app-network

  notification-service:
    container_name: notification-service
    env_file:
      - .env
    build:
      context: .
      dockerfile: /deploy/notification-service.Dockerfile
    ports:
      - "8082:${SERVER_PORT}"
    depends_on:
      - kafka
    networks:
      - app-network

  postgres-security:
    container_name: postgres-security
    image: postgres:17.4
    environment:
      POSTGRES_DB: ${SECURITY_POSTGRES_DB}
      POSTGRES_USER: ${SECURITY_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${SECURITY_POSTGRES_PASSWORD}
    ports:
      - "${SECURITY_POSTGRES_PORT}:5432"
    volumes:
      - postgres-security-data:/var/lib/postgresql/data
      - ./deploy/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  kafka:
    container_name: kafka
    image: apache/kafka:4.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - app-network
    volumes:
      - kafka-data:/var/lib/kafka/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres-security-data:
  kafka-data:
